name: hostel_hop_super_admin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  get_it: ^7.7.0
  injectable: ^2.4.2
  google_sign_in: ^6.2.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+1
  grpc: ^3.2.4
  protobuf: ^3.1.0
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.11
  supabase: ^2.2.2

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
  line_length: 80

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
