options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: "build-super-admin-frontend"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "builds",
        "submit",
        "--tag",
        "gcr.io/hostel-hop-dev/super-admin-frontend-dev",
      ]
    dir: "frontend"
  - id: "deploy-super-admin-frontend"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "super-admin-frontend-dev",
        "--image",
        "gcr.io/hostel-hop-dev/super-admin-frontend-dev",
        "--region",
        "europe-west6",
        "--platform",
        "managed",
        "--min-instances",
        "0",
        "--max-instances",
        "1",
        "--execution-environment",
        "gen2",
      ]
    waitFor: ["build-super-admin-frontend"]
  - id: "build-super-admin-grpc-backend"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["builds", "submit", "--tag", "gcr.io/hostel-hop-dev/super-admin-grpc-backend"]
    dir: "grpc"
  - id: "build-super-admin-grpc-envoy"
    name: "gcr.io/cloud-builders/gcloud"
    args: ["builds", "submit", "--tag", "gcr.io/hostel-hop-dev/super-admin-grpc-envoy"]
    dir: "envoy"
  - id: "deploy-sidecar-grpc"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - "beta"
      - "run"
      - "services"
      - "replace"
      - "sidecar-grpc-dev.yaml"
    dir: "."
    waitFor: ["build-super-admin-grpc-backend", "build-super-admin-grpc-envoy"]

serviceAccount: projects/hostel-hop-dev/serviceAccounts/342608150586-compute@developer.gserviceaccount.com
