apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
  name: hostelhop-super-admin-grpc
  labels:
    cloud.googleapis.com/location: "europe-west6"
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-connector: projects/norse-block-326612/locations/europe-west6/connectors/atlas-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec:
      containers:
        - image: "gcr.io/norse-block-326612/super-admin-grpc-envoy"
          ports:
            - containerPort: 8080
        - image: "gcr.io/norse-block-326612/super-admin-grpc-backend"
          env:
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_KEY
                  key: latest
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_URL
                  key: latest
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_JWT_SECRET
                  key: latest
            - name: SKYFLOW_VAULT_ID
              valueFrom:
                secretKeyRef:
                  name: VAULT_ID
                  key: latest
            - name: SKYFLOW_VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: VAULT_URL
                  key: latest
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: DB_DSN
                  key: latest
            - name: PROPERTY_OWNER_SKYFLOW_SERVICE_ACCOUNT_BASE_64
              valueFrom:
                secretKeyRef:
                  name: PROPERTY_OWNER_SKYFLOW_SERVICE_ACCOUNT_BASE_64
                  key: latest
