apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
  name: hostelhop-grpc-dev
  labels:
    cloud.googleapis.com/location: "europe-west6"
spec:
  template:
    spec:
      containers:
        - image: "gcr.io/hostel-hop-dev/super-admin-grpc-envoy"
          ports:
            - containerPort: 8080
        - image: "gcr.io/hostel-hop-dev/super-admin-grpc-backend"
          env:
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_KEY
                  key: latest
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_URL
                  key: latest
            - name: SUPABASE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: SUPABASE_JWT_SECRET
                  key: latest
            - name: SKYFLOW_VAULT_ID
              valueFrom:
                secretKeyRef:
                  name: SKYFLOW_VAULT_ID
                  key: latest
            - name: SKYFLOW_VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: SKYFLOW_VAULT_URL
                  key: latest
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: DB_DSN
                  key: latest
            - name: PROPERTY_OWNER_SKYFLOW_SERVICE_ACCOUNT_BASE_64
              valueFrom:
                secretKeyRef:
                  name: PROPERTY_OWNER_SKYFLOW_SERVICE_ACCOUNT_BASE_64
                  key: latest
