name: kontactbot_server
description: backend server for kontactbot
environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  alfred: ^1.1.1
  loggy: ^2.0.3
  http: ^1.2.1
  dotenv: ^4.2.0
  dio: ^5.4.3+1
dev_dependencies:
  test: ^1.25.4
  build_runner: ^2.4.7