#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/jordan/Developer/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/jordan/Desktop/hostel_hop_super_admin_grpc/frontend"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/jordan/Desktop/hostel_hop_super_admin_grpc/frontend/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=U1VQQUJBU0VfVVJMPWh0dHBzOi8vbnJ5c2N6ZGpyaW14c29qcnh2bHouc3VwYWJhc2UuY28=,U1VQQUJBU0VfQU5PTl9LRVk9ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW01eWVYTmplbVJxY21sdGVITnZhbko0ZG14Nklpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTVRjeE1EUXhPVGtzSW1WNGNDSTZNakF6TWpZNE1ERTVPWDAuOW1YR3ZkcExTNmd5UkNDWGRhR2xSeE5FZ2pTSjQzVU9DanpkRXF1bk5oUQ==,R09PR0xFX1dFQl9DTElFTlRfSUQ9MzQyNjA4MTUwNTg2LW44OW90YTZzNW5hODk1N251M2wwYWNocHQ5N283bzBuLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t,R09PR0xFX0NMSUVOVF9JRD0zNDI2MDgxNTA1ODYtM3Brczl0Y3Y0ZGozM2FpN2hxdTZzcWRpYnE0OTk5NHIuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20=,RkxVVFRFUl9XRUJfQ0FOVkFTS0lUX1VSTD1odHRwczovL3d3dy5nc3RhdGljLmNvbS9mbHV0dGVyLWNhbnZhc2tpdC9lZGQ4NTQ2MTE2NDU3YmRmMWM1YmRmYjEzZWNiOTQ2M2QyYmI1ZWQ0Lw=="
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/jordan/Desktop/hostel_hop_super_admin_grpc/frontend/.dart_tool/package_config.json"
