name: hostel_hop_super_admin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.5.6
  get_it: ^7.7.0
  injectable: ^2.4.2
  google_sign_in: ^6.2.1
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.0
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4+1
  grpc: ^3.2.4
  protobuf: ^3.1.0
  flutter_hooks: ^0.20.5
  data_table_2: ^2.5.15
  anim_search_bar: ^2.0.3
  animate_do: ^3.3.4
  google_fonts: ^6.2.1
  sentry_flutter: ^8.7.0
  package_info_plus: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.11
  supabase: ^2.2.2
  sentry_dart_plugin: ^1.0.0

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
  line_length: 80

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  upload_sources: false
  project: hostel_hop_super_admin
  org: hostel-hop-iv
  auth_token: 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
  wait_for_processing: true
  log_level: error
  commits: auto
  ignore_missing: true
  web_build_path: build/web
